### ISSUE TITLE
Bot only works if spawned using the say command but not with aeiou.

### ISSUE THREAD

**Issue by moonstar-x** [moonstar-x/discord-tts-bot#34]
#### :bug: Describe the Bug

If the bot is not in a channel prior and aeiou command is used, the bot join but will not send any TTS, even if say command is used. Once this happens, the console log displays a 400 request error.

The bot only works if spawned using the say command. Any aeiou command will only work if the bot was already in a channel.

#### :pencil2: Steps to Reproduce

> 1. The bot is not connected to voice.
> 2. Run aeiou command
> 3. Bot joins but is stuck in an unexpected state

#### :confused: Expected Behavior

The bot should be able to send TTS even if spawned using aeiou.

#### :scroll: Log

``` text
Mar 12 20:42:41 moonstar-server npm[29941]: (8:42:41 PM) - [INFO] -  User yoo who did dis 😂😂 issued command aeiou in Greencoast Gaming.
Mar 12 20:42:42 moonstar-server npm[29941]: (8:42:42 PM) - [INFO] -  Joined 🦇 LA BATICUEVA 🦇 in Greencoast Gaming.
Mar 12 20:42:42 moonstar-server npm[29941]: (8:42:42 PM) - [ERROR] -  Request failed with status code 400
```

#### :question: Other Information

* Node Version: `14.9.0`

**Comment by moonstar-x** [comment]
Fixed in #39.

**Comment by haloflooder** [comment]
> 
> 
> Fixed in #39.

Didn't want to create a new issue but it seems like this problem still exists.

I'm hosting the bot via docker with docker-compose and when you use "aeiou", it does nothing. Then when you try to use "say", the bot no longer says anything.

**Comment by moonstar-x** [comment]
Have you tried updating your container to the latest image?

I haven't had this issue in a really long time and I've been hosting the bot for over 200 servers. Do you get a 400 error code as well?

**Comment by haloflooder** [comment]
I put it up a fresh instance 2 days ago but just pulled the latest image right now just in case. Seems like the problem still exists on my side and not sure what could be causing it. Going to try hosting it somewhere else to see if it's somehow an issue with the connection on the current host I'm using.

I don't get any 400 error code in console or dm's.

I also discovered that instead of just restarting the docker container to get it unstuck, you can just use the stop command then use say afterwards. After the aeiou clip plays nothing (it shows "Playing aeiou for <msg>" in console), the bot doesn't play any other clips from say or aeiou.

![console logs](https://i.imgur.com/HiclmwY.png)

Just for reference, this is the docker compose I'm using in case you wanted to see it
```yml
version: "3.2"

services:
  obbytts:
    image: moonstarx/discord-tts-bot
    restart: always
    environment:
      DISCORD_TOKEN: "<redacted>"
      DISCORD_PREFIX: "."
      DISCORD_OWNER_ID: 136676457987571713
```

**Comment by moonstar-x** [comment]
Hmmm, this is weird, it doesn't seem like it's related to the initial problem from this issue.

This kinda looks like aeiou doesn't work altogether for you, not that using aeiou first (making the bot join the channel with aeiou) would break subsequent requests.

It could certainly be the host you're using that cannot connect to the url from where the aeiou tts is being pulled.

Are you hosting on firebase / google cloud platform by any chance?
